# We explicitly don't use a container for running the job since there is some connectivity issues to MySQL if that is done
# needed because the mysql container does not provide a health check
# use localhost for the host here because we have specified a vm for the job.
# '>-' is a special YAML syntax and means that new lines would be replaced with spaces
# and new lines from the end would be removed

name: Modified Flowable MySQL Build
env:
  MAVEN_ARGS: -Dmaven.javadoc.skip=true -B -V --no-transfer-progress -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  test_mysql:
    name: test_mysql (${{ matrix.mysql }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql:
        - 5.7
        - 8.0
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_DATABASE: flowable
          MYSQL_USER: flowable
          MYSQL_PASSWORD: flowable
          MYSQL_ROOT_PASSWORD: flowable
        ports:
        - 3306/tcp
        options: --health-cmd="mysqladmin -uflowable -pflowable status" --health-interval
          10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_mysql (${{ matrix.mysql }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/flowable-engine/flowable-engine', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Set MySQL collation
      run: docker exec ${{ job.services.mysql.id }} sh -c 'mysql --user=flowable --password=flowable
        --database=flowable --execute="alter database flowable character set utf8mb4
        collate utf8mb4_bin"'
    - run: touch optcd-3.txt
    - uses: actions/checkout@v4
    - run: touch optcd-4.txt
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - run: touch optcd-5.txt
    - name: Test
      run: ./mvnw clean install ${MAVEN_ARGS} -PcleanDb,mysql,distro -P'!include-spring-boot-samples'
        -Djdbc.url=jdbc:mysql://localhost:${{ job.services.mysql.ports[3306] }}/flowable?characterEncoding=UTF-8
        -Djdbc.username=flowable -Djdbc.password=flowable -Djdbc.driver=com.mysql.cj.jdbc.Driver
        -Dspring.datasource.url=jdbc:mysql://localhost:${{ job.services.mysql.ports[3306]
        }}/flowable?characterEncoding=UTF-8 -Dspring.datasource.username=flowable
        -Dspring.datasource.password=flowable -Dmaven.test.redirectTestOutputToFile=false
    - run: touch optcd-6.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_mysql (${{ matrix.mysql }})
        path: /home/runner/inotifywait-log-test_mysql (${{ matrix.mysql }}).csv
'on':
- push
- workflow_dispatch
